library(plotly)
library(shinyWidgets)
library(shinydashboard)
library(shinydashboardPlus)
library(DT)
library(magrittr)
library(shinycustomloader)
library(rtsdata)

source('R/functions.R', encoding = 'UTF-8')